### ISSUE TITLE
Signs for Gods making

### ISSUE THREAD

**Issue by ghost** [DogOnFire/Gods#8]
When I write on any type of sign (oak, spruce, birch ...) the name of the deity does not turn into "**Altar of X**". This error also occurs with the blocks indicated in the configuration file for the different deities and in other blocks such as the Stone bricks. This in Minecraft 1.14.2

**Comment by HeroGamers** [comment]
@MrKokko03 
I am not getting this issue on my fork atm., for now the only Signs which are accepted are Oak Signs.

Edit: This branch on Gods works too for me, are you sure you remembered the Torch? Try compiling again

**Comment by ghost** [comment]
I'm sorry, i was using the compiled version on Bukkit (0.9.0) after i compiled it it worked, thanks!
